#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DrawApps.Resource", IsApplication=true)]

namespace DrawApps
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int blue = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int green = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int red = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050003
			public const int large_brush = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int medium_brush = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int pencil = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int small_brush = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int brush = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int brush2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int erase2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int eraser = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int large = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int medium = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int new2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int new_pic = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int paint = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int paint_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int pencil2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int save = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int save2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int small = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ToggleBtn = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int brush_size_chooser = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int draw_btn = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int drawing = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int erase_btn = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int large_brush = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int medium_brush = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int new_btn = 2131230724;
			
			// aapt resource value: 0x7f08000a
			public const int paint_colors = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int pencil_btn = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int save_btn = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int small_brush = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060003
			public const int large_size = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int medium_size = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int pencil_size = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int small_size = 2131099649;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int brush_chooser = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int brush = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int erase = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int lrg = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int med = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int paint = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int pencil = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int save = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int sml = 2131165192;
			
			// aapt resource value: 0x7f070002
			public const int start_new = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
